### PR TITLE
add JavaScript 5 formatter for Eclipse

### PR DESCRIPTION
**Pull request by outofthecave**
@Mmdixon @tavianator @freeone3000 I'll be using this formatter when writing the JavaScript code for Native Dialogue.  It looks similar to our Java 8 formatter.  If you disagree with any of the style choices I've made, please comment on this PR.

### CODE REVIEW

**Comment by Mmdixon** [comment]
is there a way to run this without eclipse?

**Comment by outofthecave** [comment]
Idk.  For Java, we run the formatter through maven.  Maybe we can get the thing that builds NativeNlp to run it for us?

**Comment by macadada** [comment]
Yea we should use something like eslint and just make it part of the build step.  http://eslint.org/

**Comment by outofthecave** [comment]
Good idea.  But I still want a formatter in Eclipse in addition to that, so I can hit Ctrl+Shift+F instead of having to build the entire project (which I would probably have to do on the command line).

**Pull request closed without merging**
